<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Xhgui_' => array($baseDir . '/../src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Slim' => array($vendorDir . '/slim/slim'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
);
